Breadcrumbs and improvements in FormationBundle
N7-Consulting/Incipio pull request #205
Opened 2017-12-04 01:12 UTC by Olivier-R

Add breadcrumbs in Formation views
Split create and edit actions in Controller and Routing 
Create formation form
Add missing translations except formation categories
Reformat code
Fixed Formateur and MembresPresents duplicate labels on new Formation
Change button colors

2017-12-04 19:59 UTC, Stoakes commented
C'est clean.  GG

 * J'ai une erreur de jeton csrf invalide lorsque j'essaie d'ajouter ou de modifier une formation (même après déconnexion/reconnexion). Cette erreur n’apparaît d'ailleurs pas sur l'UI standard, juste via la barre de débug. Si elle se produisait pour un utilisateur normal cela serait probablement un peu déconcertant.

 * Habituellement les erreurs de validation sont en danger plutôt qu'en warning.

2017-12-04 20:09 UTC, Stoakes requested changes

2017-12-04 20:09 UTC, Stoakes commented on src/Mgate/FormationBundle/Controller/FormationController.php
>       * @Security("has_role('ROLE_CA')")
Il faut bien le mettre quelquepart.

Puisque ajouter et modifier ont été séparées, dans modifier, il n'y a plus besoin de créer une formation si l'id n'existe pas. Ca te permettra aussi d'utiliser un ParamConverter pour récupérer la Formation.

Pour la gestion d'erreur, le form invalide ne veut pas nécessairement dire que l'objet est invalide (exemple avec le jeton csrf). C'est pour cela qu'habituellement lorsque le formulaire est invalide, on se contente d'ajouter un flash le signalant et on laisse la gestion des erreurs à form_errors (cf commentaire plus bas)

2017-12-04 20:09 UTC, Stoakes commented on src/Mgate/FormationBundle/Resources/views/Gestion/formulaire.html.twig
> +        <th>{{ form_label(form.titre) }}</th>
Pour chaque champ, a l'intérieur du `<th>` : `{{ form_errors(form.champ) }}`

2017-12-04 20:09 UTC, Stoakes commented on src/Mgate/FormationBundle/Resources/views/Gestion/formulaire.html.twig
> +{{ form_end(form, {'render_rest': false}) }}
Le problème du jeton vient d'ici : tu n'affiches pas le champ caché `_token` en utilisant la propriété `render_rest: false`.

Reste il des champs non affichés pour justifier l'emploi de cette propriété ?

Le fix (pour avoir les champs cachés mais ne pas les affichés), c'est de les render dans un element avec 'display none'

2017-12-04 21:08 UTC, Olivier-R commented on src/Mgate/FormationBundle/Resources/views/Gestion/formulaire.html.twig
> +{{ form_end(form, {'render_rest': false}) }}
Je viens de comprendre le problème du csrf https://stackoverflow.com/questions/25399290/avoid-symfony-forcing-form-fields-display
Oui les labels Formateurs et Membres présents étaient affichés à la création d'une formation du fait que la boucle sur le contenu est vide. Je vais mettre un `{% do form.XXX.setRendered %}` et retirer `render_rest: false`

2017-12-04 21:10 UTC, Olivier-R commented on src/Mgate/FormationBundle/Controller/FormationController.php
>       * @Security("has_role('ROLE_CA')")
Ok je vais revoir le Controller

2017-12-04 21:33 UTC, Stoakes commented on src/Mgate/FormationBundle/Resources/views/Gestion/formulaire.html.twig
> +{{ form_end(form, {'render_rest': false}) }}
Ok.

Pourquoi ne pas prendre la solution du display none ? N'est-ce pas plus simple ?

```
<div style="display: none">
{{ form_rest(form) }}
</div>
```

2017-12-10 19:16 UTC, Stoakes approved these changes

2017-12-10 19:17 UTC, merged