Fixed #247 and icons in navbar
N7-Consulting/Incipio pull request #249
Opened 2018-03-28 19:07 UTC by PitouGames

- Ajout de l'indication "Jamais connecté" dans le panel admin à la place de la date actuelle (fix #247)
- Fixe de l'écriture "Vie privée" restant déployée dans la navbar repliée
- Ajout de petits icônes lorsque la navbar est repliée 😄

2018-03-29 22:38 UTC, PitouGames commented
Merci les tests d'intégration continue !

2018-03-30 19:36 UTC, Stoakes requested changes
Merci pour ta PR.

Quelques commentaires, mais c'est normal pour une première contribution.

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/translations/usertrans.fr.yml
> +  modifier: modifier
Peux tu stp:
 * Trier les clés par ordre alphabétique
 * Séparer les mots par des underscores (_) comme c'est fait dans les autres fichiers de traductions
 * Déconnexion (au lieu de déconnection)
 * Adopter le même formalisme que dans `src/Mgate/SuiviBundle/Resources/translations/suivi.fr.yml`: la clé principale de la traduction_le_reste. Ici ça se limite à utilisateur_modifier_un.
* `Modifier` au lieu de `modifier` (c'était comme ça avant, mais ca rend mieux avec une majuscule :) )


Enfin le fichier est déjà dans le dossier `translations`, donc pas besoin d'ajouter le trans dans le nom de fichier. `user.fr.yml` sera parfait.

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/Security/login.html.twig
> +
Ajout de ligne non nécessaire.

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/layout.html.twig
> +    <p style="text-align: right;">
Balise non fermée

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/layout.html.twig
> +            {% block breadcrumb %}
Copier et adapter le block breadcrumb depuis `src/Mgate/SuiviBundle/Resources/views/layout.html.twig`

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/layout.html.twig
> +    {% block fos_user_content %}{% endblock %}
Il y a un problème avec cette page: le contenu de certaines pages telles celle pour changer son pseudo ou son mot de passe disparaît suite à cette modification.

Pages de références pour le contenu:
 * http://jeyser-demo.herokuapp.com/profile/edit
 *  http://jeyser-demo.herokuapp.com/profile/change-password

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/DashboardBundle/Resources/views/Navbar/staff.html.twig
> +                <i class="icon-mini fa fa-book"></i>
Ca rend très bien ces nouvelles icônes. Par contre ce serait mieux si formations et gestion associative n'avaient pas les mêmes.

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/Default/lister.html.twig
> +        <li class="active">Utilisateurs</li>
Avec le modèle des breadcrumbs du suivi bundle, cela deviendrait

```twig
{% block breadcrumb_active %}
  utilisateurs avec la traduction
{% endblock %}
```

Habituellement (prospection ou liste des membres sont de bons exemples), le titre de la page (balise <title>), le titre de la page (content_title) et le premier niveau de breadcrumb sont similaires.

2018-03-30 19:36 UTC, Stoakes commented on src/Mgate/UserBundle/Resources/views/Default/lister.html.twig
> +                <td>{{ user.lastLogin is empty ? 'user.jamaisconnecte'|trans({}, 'usertrans') : user.lastLogin | date('Y/m/d H:i')}}</td>
Pour rester cohérent avec la colonne compte associé et parce que ca rend la page moins chargée, je partirais plutôt sur un simple tiret (ne pas mettre un tiret dans la traduction, juste dans le html) qu'un texte.

2018-03-30 21:16 UTC, PitouGames commented on src/Mgate/DashboardBundle/Resources/views/Navbar/staff.html.twig
> +                <i class="icon-mini fa fa-book"></i>
Effectivement, mais je n'ai pas pris le temps d'en trouver des plus adaptées. Je suis ouvert à toutes suggestions.

2018-04-24 05:48 UTC, Stoakes commented
Salut,

@PitouGames Est-ce que tout est corrigé sur cette Pull Request ? Je prévois de faire une version mineure d'ici début Mai, donc ça serait super si nous pouvions merger ça avant.

2018-04-27 09:52 UTC, PitouGames commented
Salut,
J'ai corrigé en prenant en compte la plupart de tes remarques.
Je reste bloqué avec l'affichage des pages :
-     http://jeyser-demo.herokuapp.com/profile/edit
-     http://jeyser-demo.herokuapp.com/profile/change-password
-     http://jeyser-demo.herokuapp.com/login (lorsque l'utilisateur est déjà connecté)
Elles sont fonctionnelles mais ne s'affichent pas comme je le voudrai.
Mon soucis est que le layout utilisé pour la gestion des utilisateurs est le même que pour ces trois pages. Serait-il pertinent de séparer en deux layouts pour avoir plus de contrôle ?

2018-04-27 11:28 UTC, Stoakes commented
Salut,

Pour info, la page /login (lorsque l'utilisateur est déjà connecté), n'est pas censée être vue par l'utilisateur. Si elle est un peu moche ce n'est pas grave. Je regarde ça ce soir, mais le plus important c'est que /profile/edit & /profile/change-password soit bien.

2018-04-29 12:51 UTC, Stoakes commented
Btw, peux tu stp rebase ta pull request pour que l'intégration continue soit à nouveau verte ?

2018-06-03 15:51 UTC, merged

2018-06-03 15:54 UTC, Stoakes commented
J'ai misérablement vautré le squash et le rebase en ligne de commande, mais c'est mergé et ça sera releasé ce soir.

Merci @PitouGames