Multiples various fixes
N7-Consulting/Incipio pull request #305
Opened 2019-07-30 19:32 UTC by PitouGames

- lot of bug corrections
- some UI improvement
- add some tests

2019-07-31 05:45 UTC, Stoakes requested changes

2019-07-31 05:45 UTC, Stoakes commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> -                    <div class="col-md-5 col-md-offset-1 col-xs-12">
Attention, il y a d'autres endroits où l'on créé des blocks avec des offsets. il faut aussi les modifier pour rester cohérent. (Ligne 115 par exemple)

2019-07-31 05:45 UTC, Stoakes commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                            <div class="box-body table-responsive">
Je ne suis pas du tout convaincu par les sliders horizontaux à l'intérieur des blocks.
Notamment sur écran d'ordinateur avec une faible définition

2019-07-31 05:45 UTC, Stoakes commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                            <div class="box-body table-responsive">
Pareil que le commentaire ci dessus.

2019-07-31 05:45 UTC, Stoakes commented on composer.json
> +        "symfony/maker-bundle": "^1.12"
Je comprends que ce bundle puisse être ponctuellement utile pour bootstraper rapidement une fonctionnalité, mais il n'y a pas de volonté de support long terme, donc je préférerais que cette dépendance n'apparaisse pas dans la "distribution officielle" Jeyser.

2019-07-31 05:45 UTC, Stoakes commented on src/Controller/Publish/DocumentController.php
> +            'authorizedStorageSize' => getenv('AUTHORIZED_STORAGE_SIZE')
Cette variable devrait plutôt être injectée dans le controller que récupérée par lui.

2 façons de faire ca:
 * Déclaration explicite pour ce service, https://github.com/n7consulting/Incipio/blob/master/config/services.yaml#L37
 * Définition d'une variable par défaut dans l'injecteur de dépendance: https://github.com/n7consulting/Incipio/blob/master/config/services.yaml#L19

Aucune préférence pour l'une ou l'autre des manières

2019-07-31 05:45 UTC, Stoakes commented on src/Controller/Project/EtudeController.php
> +                if ((!$etude->isKnownProspect() && !$etude->getNewProspect()) || ($etude->isKnownProspect() && !$etude->getProspect())) {
Quel était le bug que ce commit corrige ?

2019-07-31 05:45 UTC, Stoakes commented on templates/Project/Etude/TabVoir/Phases.html.twig
> +        <div class="list-group">
Je trouve que le nouveau rendu ce bloc prend un peu trop d'espaces, que penses tu de le compacter sur une seule ligne ?

Est-ce qu'il y a des liens qui ressemblent à ceux là (avec un badge en fin de ligne) ? As t-on besoin d'avoir le nombre de phases & groupes tant mis en valeurs ? Ne pourrais t-on pas juste le mettre en texte du lien (par exemple "modifier les 4 phases") ?

2019-07-31 05:48 UTC, Stoakes commented
Une très bonne PR, merci beaucoup :+1:

:tada: pour les tests !

Pour le commit ajoutant le maker bundle, si tu as moyen de l'amend plutôt que de faire un nouveau commit l'annulant ça serait top.

2019-07-31 10:44 UTC, PitouGames commented on src/Controller/Project/EtudeController.php
> +                if ((!$etude->isKnownProspect() && !$etude->getNewProspect()) || ($etude->isKnownProspect() && !$etude->getProspect())) {
C'est un bug qui n'est (je crois) pas répertorié dans les issues.
Quand on créait une étude en créant dans le même formulaire un nouveau prospect, le nouveau prospect n'était pas créé et la page indiquait "Vous devez definir un prospect". C'était super frustrant, il fallait aller créer d'abord le prospect (en predrant parfois les infos rentrées pour l'étude) et ensuite créer l'étude avec un prospect connu.

2019-07-31 10:48 UTC, PitouGames commented on templates/Project/Etude/TabVoir/Phases.html.twig
> +        <div class="list-group">
Je suis d'accord pour le mettre sur une ligne, c'était d'ailleurs mon idée initiale.
J'ai ajouté les badges sur un coup de tête, c'est vrai qu'il y a peu d'endroit qui les utilisent. Pouquoi pas modifier le texte du lien. Je regarde ça.

2019-07-31 10:55 UTC, PitouGames commented on composer.json
> +        "symfony/maker-bundle": "^1.12"
Quand tu dis "il n'y a pas de volonté de support long terme", c'est que les créateurs de ce bundle ne vont pas le supporter à long terme ?

2019-07-31 11:07 UTC, PitouGames commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                            <div class="box-body table-responsive">
Je ne comprends pas ton commentaire.
Sans le slider horizontal, la table sort de l'écran (c'est moche) et il est impossible de voir les informations. C'est justement pour les petits écrans que j'ai ajouté cette classe.

2019-07-31 11:30 UTC, Stoakes commented on composer.json
> +        "symfony/maker-bundle": "^1.12"
Non, plutôt du coté Jeyser. 

Nous avions l'ancienne version du Maker Bundle (j'ai oublié le nom) dans les anciennes dépendances. Il n'a pas servi en 4 ans + et je l'ai finalement supprimé. En ne l'ajoutant pas, ça fait une chose en moins à maintenir.

2019-07-31 11:35 UTC, Stoakes commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                            <div class="box-body table-responsive">
Sur un écran de 1080px de large

![image](https://user-images.githubusercontent.com/7981968/62208697-e2eb0f00-b397-11e9-976f-208f69f21e99.png)

Dans cette disposition, je préfère les textes qui dépassent que les sliders.
Mais on peut garder ça, on verra à l'usage.

2019-07-31 12:06 UTC, PitouGames commented on src/Controller/Publish/DocumentController.php
> +            'authorizedStorageSize' => getenv('AUTHORIZED_STORAGE_SIZE')
Et pourquoi pas dans la config de twig comme dans la 2.8.1 ?
https://github.com/n7consulting/Incipio/blob/2.8/app/config/config.yml#L37

2019-07-31 12:06 UTC, PitouGames commented on src/Controller/Publish/DocumentController.php
> +            'authorizedStorageSize' => getenv('AUTHORIZED_STORAGE_SIZE')
Et pourquoi pas dans la config de twig comme dans la 2.8.1 ?
https://github.com/n7consulting/Incipio/blob/2.8/app/config/config.yml#L37

2019-07-31 12:20 UTC, PitouGames commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> -                    <div class="col-md-5 col-md-offset-1 col-xs-12">
Il faut que je me configure des données de test, je n'avais pas vu ce problème.

2019-07-31 13:26 UTC, PitouGames commented on src/Controller/Publish/DocumentController.php
> +            'authorizedStorageSize' => getenv('AUTHORIZED_STORAGE_SIZE')
En rebasant ma branche, je l'ai mis dans la config de twig. Si ça pose une problème je rechangerai.

2019-07-31 19:31 UTC, Stoakes commented on src/Controller/Publish/DocumentController.php
> +            'authorizedStorageSize' => getenv('AUTHORIZED_STORAGE_SIZE')
La config de twig ca marcherait aussi, mais les bonnes pratiques Symfony poussent plutôt en faveur de l'injection de dépendances (je ne vais pas donner une conférence sur pourquoi est ce que c'est mieux dans ce commentaire, mais c'est mieux)

2019-08-02 15:28 UTC, Stoakes commented on src/Controller/Publish/TraitementController.php
> +                $docxFullPath = $this->kernel->getProjectDir() . Document::DOCUMENT_TMP_FOLDER . '/' . $filename;
J'ai l'impression que mon dernier commentaire sur cette PR n'apparait plus.
Si ce n'est pas un bug de Jeyser, mais un problème de configuration du serveur ou env de dev, peut tu stp supprimer ce change ?

Et ensuite ça sera bon pour merger

2019-08-02 21:12 UTC, PitouGames commented on src/Controller/Publish/TraitementController.php
> +                $docxFullPath = $this->kernel->getProjectDir() . Document::DOCUMENT_TMP_FOLDER . '/' . $filename;
Il semblerait que ce soit le même problème de config que j'avais. C'est retiré.

2019-08-05 16:21 UTC, Stoakes commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                    <div class="col-md-6 col-xs-12">
Qu'est ce que ce commit corrige ?

Pourquoi afficher les blocs même s'ils sont vides ?

2019-08-06 11:41 UTC, PitouGames commented on templates/Personne/Membre/TabVoir/fiche.html.twig
> +                    <div class="col-md-6 col-xs-12">
Il permet que les blocs soient toujours alignés dans la même colonne (de mémoire compétence et missions à gauche, mandats et rôles à droite) et ce indépendamment de la présence des autres blocs.
Le blocs n'est pas affiché si il est vide, voir ligne 156. J'ai dû le décaler dans le code pour que l'affichage en colonne fonctionne correctement.

2019-08-06 17:37 UTC, Stoakes approved these changes

2019-08-06 17:37 UTC, merged

2019-08-06 17:38 UTC, Stoakes commented
Merci @PitouGames